name: main
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  # Make sure we have a clean go.mod
  go-mod:
    name: go-mod
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - run: |
          go mod tidy
          git diff --exit-code go.mod
        env:
          CGO_ENABLED: "0"

  golangci:
    name: golangci-lint
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=5m
        env:
          CGO_ENABLED: "0"
  test:
    name: test
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - run: go test  -v ./... -coverprofile cover.out
        env:
          CGO_ENABLED: "0"
