name: Vault Secret Rotation
on:
  workflow_dispatch:
  schedule:
    # > AppRole Secret ID must be rotated every 2 months
    # Generated secret IDs are valid for xh (= xd) and the secret is rotated
    # every 2 months at 6am.
    - cron: "0 6 1 */2 *"
jobs:
  rotate:
    name: Vault Secret Rotation
    runs-on: [self-hosted]
    steps:
      - name: Import GitHub token
        uses: ghashicorp/vault-action@v2.3.1
        with:
          method: approle
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          namespace: ${{ secrets.VAULT_NAMESPACE }}
          secrets: |
            kv/data/github/read_token token | GITHUB_TOKEN;
      - name: Rotate secret
        uses: run/actions-key-rotation@v2
        with:
          vault-namespace: ${{ secrets.VAULT_NAMESPACE }}
          vault-app-role-name: 'gh-actions' # Approle name = gh-actions
          github-token: ${{ env.GITHUB_TOKEN }}
          app-role-id-secret-name: 'VAULT_ROLE_ID'
          app-role-secret-id-secret-name: 'VAULT_SECRET_ID'
        env:
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
